ensure_value_type(false and false, false, "bool")
ensure_value_type(true and false, false, "bool")
ensure_value_type(false and true, false, "bool")
ensure_value_type(true and true, true, "bool")
ensure_value_type(nil and false, nil, "nil")
ensure_value_type(false and nil, false, "bool")
ensure_value_type(true and nil, false, "nil")
ensure_value_type(nil and true, nil, "nil")

ensure_value_type(1 and false, false, "bool")
ensure_value_type(1 and {}, {}, "table")
ensure_value_type("5" and 2, 2, "int")
ensure_value_type("5" and "4", "4", "string")
ensure_value_type({ 1, 2, 3 } and #"toto", 4, "int")
ensure_value_type(0 and 0, 0, "int")
